# CircleCI configuration file

version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/python:3.11.6
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r test-requirements.txt
      - run:
          name: Install MetaGen
          command: pip install .
      - run:
          name: Run tests
          command: pytest test/

workflows:
  test:
    jobs:
      - run_tests