# CircleCI configuration file

version: 2.1

jobs:
  run_tests:
    docker:
      - image: cimg/python:3.11.6
    resource_class: small
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r test-requirements.txt
      - run:
          name: Install MetaGen
          command: pip install .
      - run:
          name: Run tests
          command: pytest test/
          
  run_tests_win:
    machine:
      image: 'windows-server-2022-gui:current'
    resource_class: windows.medium
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r test-requirements.txt
      - run:
          name: Install MetaGen
          command: pip install .
      - run:
          name: Run tests
          command: pytest test/

  run_tests_mac:
    macos:
      xcode: "14.2.0"
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r test-requirements.txt
      - run:
          name: Install MetaGen
          command: pip install .
      - run:
          name: Run tests
          command: pytest test/

workflows:
  test:
    jobs:
      - run_tests
      - run_tests_win
      - run_tests_mac